import { StyleSheet } from "react-native";

export const recipeDatabaseDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    gap: 16,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0f172a",
    textAlign: "center",
  },
  backButton: {
    backgroundColor: "#128AFA",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  backButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#e0f2fe",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
    marginHorizontal: 12,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  heroWrapper: {
    height: 240,
    borderRadius: 24,
    marginHorizontal: 20,
    overflow: "hidden",
    marginBottom: 20,
    justifyContent: "flex-end",
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#fff",
    padding: 20,
    textShadowColor: "rgba(15,23,42,0.4)",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
  },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  statPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#e0f2fe",
  },
  statLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0f172a",
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 12,
  },
  sectionBody: {
    fontSize: 16,
    lineHeight: 24,
    color: "#334155",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 18,
    gap: 12,
    shadowColor: "#94a3b8",
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 3,
  },
  listItem: {
    fontSize: 15,
    lineHeight: 22,
    color: "#1e293b",
  },
  stepRow: {
    flexDirection: "row",
    gap: 14,
    alignItems: "flex-start",
  },
  stepBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#128AFA",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  stepBadgeText: {
    color: "#fff",
    fontWeight: "700",
  },
  stepText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: "#1f2937",
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tagPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#e0f2fe",
  },
  tagText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#0f172a",
  },
  loaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  loaderLabel: {
    color: "#475569",
    fontSize: 14,
  },
  sourceHint: {
    textAlign: "center",
    fontSize: 13,
    color: "#64748b",
    marginBottom: 32,
  },
  ctaButton: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    borderRadius: 18,
    backgroundColor: "#128AFA",
    shadowColor: "#2563eb",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 20,
    elevation: 6,
  },
  ctaText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  matchBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  matchBadgeHigh: {
    backgroundColor: "#d1fae5",
  },
  matchBadgeMedium: {
    backgroundColor: "#fed7aa",
  },
  matchBadgeLow: {
    backgroundColor: "#fecaca",
  },
  matchBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0f172a",
  },
  ingredientRow: {
    marginBottom: 4,
  },
  ingredientButton: {
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginVertical: 2,
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ingredientButtonLoading: {
    backgroundColor: "#f1f5f9",
    borderColor: "#128AFA",
  },
  ingredientButtonActive: {
    backgroundColor: "#e0f2fe",
    borderColor: "#128AFA",
  },
  ingredientButtonAvailable: {
    backgroundColor: "#f8fafc",
    borderColor: "#e2e8f0",
  },
  missingIngredient: {
    color: "#dc2626",
    fontWeight: "600",
  },
  partialIngredient: {
    color: "#d97706",
    fontWeight: "600",
  },
  availableIngredient: {
    color: "#1e293b",
    fontWeight: "400",
  },
  miniLoader: {
    marginLeft: 8,
  },
  substituteContainer: {
    marginTop: 8,
    marginLeft: 16,
    marginBottom: 12,
    paddingLeft: 12,
    borderLeftWidth: 3,
    borderLeftColor: "#128AFA",
    backgroundColor: "#f0f9ff",
    borderRadius: 8,
    padding: 12,
  },
  substituteHeader: {
    fontSize: 13,
    fontWeight: "700",
    color: "#128AFA",
    marginBottom: 8,
  },
  substituteRow: {
    marginBottom: 8,
  },
  substituteContent: {
    gap: 4,
  },
  substituteName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0f172a",
  },
  substituteReason: {
    fontSize: 12,
    color: "#64748b",
    fontStyle: "italic",
    lineHeight: 18,
    paddingLeft: 12,
  },
  ingredientHint: {
    marginTop: 12,
    fontSize: 12,
    color: "#64748b",
    fontStyle: "italic",
    textAlign: "center",
  },
  // Cooking Mode Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  modalCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fee2e2",
    alignItems: "center",
    justifyContent: "center",
  },
  modalHeaderTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
    textAlign: "center",
    marginHorizontal: 12,
  },
  modalScroll: {
    flex: 1,
  },
  modalScrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  progressSection: {
    marginBottom: 24,
    padding: 16,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  progressText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0f172a",
    marginBottom: 12,
  },
  progressBar: {
    height: 8,
    backgroundColor: "#e2e8f0",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#128AFA",
    borderRadius: 4,
  },
  cookingStepCard: {
    marginBottom: 16,
    padding: 16,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#e2e8f0",
  },
  cookingStepCardCompleted: {
    backgroundColor: "#f0fdf4",
    borderColor: "#86efac",
  },
  cookingStepCardCurrent: {
    borderColor: "#128AFA",
    borderWidth: 2,
  },
  cookingStepHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  stepBadgeCompleted: {
    backgroundColor: "#22c55e",
  },
  stepBadgeTextCompleted: {
    color: "#ffffff",
  },
  checkboxButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxButtonCompleted: {
    backgroundColor: "#22c55e",
    borderColor: "#22c55e",
  },
  cookingStepText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#1e293b",
  },
  cookingStepTextCompleted: {
    color: "#15803d",
    textDecorationLine: "line-through",
  },
  markCompleteButton: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: "#128AFA",
  },
  markCompleteButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
  },
  deductSection: {
    marginTop: 32,
    gap: 16,
  },
  deductInfoCard: {
    padding: 16,
    backgroundColor: "#eff6ff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  deductInfoTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e40af",
    marginBottom: 8,
  },
  deductInfoText: {
    fontSize: 14,
    color: "#1e40af",
    lineHeight: 20,
  },
  deductButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: "#128AFA",
    shadowColor: "#128AFA",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 6,
  },
  deductButtonDisabled: {
    opacity: 0.6,
  },
  deductButtonSuccess: {
    backgroundColor: "#22c55e",
    shadowColor: "#22c55e",
  },
  deductButtonText: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "700",
  },
});
