import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export const makerStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: "transparent",
  },
  backButton: {
    marginRight: 12,
    padding: 8,
    borderRadius: 12,
    backgroundColor: Colors.primary.lightest,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: Colors.neutral.black,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    gap: 20,
  },
  section: {
    backgroundColor: Colors.neutral.white,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.neutral.light,
    shadowColor: Colors.neutral.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  label: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.neutral.black,
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 2,
    borderColor: Colors.neutral.gray,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: Colors.neutral.black,
    backgroundColor: Colors.neutral.lightest,
  },
  multilineInput: {
    height: 120,
    textAlignVertical: "top",
    paddingTop: 14,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: Colors.neutral.lighter,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: Colors.neutral.black,
    letterSpacing: 0.5,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: Colors.accent.successLightest,
    borderWidth: 1.5,
    borderColor: Colors.accent.success,
    shadowColor: Colors.accent.success,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  addButtonText: {
    color: Colors.accent.successDark,
    fontWeight: "700",
    fontSize: 14,
  },
  ingredientRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
    padding: 12,
    backgroundColor: Colors.neutral.lightest,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.neutral.light,
  },
  ingredientName: {
    flex: 2,
  },
  ingredientQty: {
    width: 70,
  },
  unitContainer: {
    width: 80,
    borderWidth: 2,
    borderColor: Colors.neutral.gray,
    borderRadius: 14,
    backgroundColor: Colors.neutral.lightest,
    justifyContent: "center",
  },
  unitPicker: {
    height: 48,
    color: "#0f172a",
  },
  removeButton: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: Colors.error.lightest,
    borderWidth: 1,
    borderColor: Colors.error.lighter,
  },
  stepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
    padding: 14,
    backgroundColor: Colors.neutral.lightest,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.neutral.light,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary.main,
  },
  stepNumberContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.primary.main,
    shadowColor: Colors.primary.main,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  stepNumber: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.neutral.white,
  },
  stepInput: {
    flex: 1,
    minHeight: 90,
    paddingTop: 14,
  },
  buttonGroup: {
    gap: 14,
    marginTop: 16,
    paddingHorizontal: 4,
  },
  primaryButton: {
    backgroundColor: Colors.secondary.main,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.secondary.main,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: Colors.secondary.dark,
  },
  primaryButtonText: {
    color: Colors.neutral.white,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  secondaryButton: {
    backgroundColor: Colors.primary.main,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.primary.main,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: Colors.primary.dark,
  },
  secondaryButtonText: {
    color: Colors.neutral.white,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  disabledButton: {
    opacity: 0.5,
  },
  fullWidthButton: {
    width: '100%',
  },
  landscapeContainer: {
    flexDirection: "column", // To stack sections in landscape mode
    gap: 20,
    width: "100%",
  },
  landscapeColumn: {
    width: "100%", // Stacking in landscape mode
    gap: 20,
  },
  sectionSubtitle: {
    fontSize: 13,
    color: Colors.neutral.medium,
    marginBottom: 12,
    marginTop: -8,
  },
  equipmentGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  equipmentChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.neutral.light,
    backgroundColor: Colors.neutral.white,
  },
  equipmentChipSelected: {
    borderColor: Colors.primary.main,
    backgroundColor: Colors.primary.lightest,
  },
  equipmentIcon: {
    fontSize: 18,
  },
  equipmentName: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.neutral.dark,
  },
  equipmentNameSelected: {
    color: Colors.primary.main,
  },
  // Difficulty Selection
  difficultyContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 8,
  },
  difficultyChip: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.neutral.light,
    backgroundColor: Colors.neutral.white,
    alignItems: "center",
  },
  difficultyChipSelected: {
    borderColor: Colors.primary.main,
    backgroundColor: Colors.primary.lightest,
  },
  difficultyChipText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.neutral.dark,
  },
  difficultyChipTextSelected: {
    color: Colors.primary.main,
  },
  // Tags Selection
  tagCategoryLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.neutral.medium,
    marginTop: 16,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tagsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tagChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.neutral.light,
    backgroundColor: Colors.neutral.white,
  },
  tagChipSelected: {
    borderColor: Colors.primary.main,
    backgroundColor: Colors.primary.lightest,
  },
  tagChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.neutral.dark,
  },
  tagChipTextSelected: {
    color: Colors.primary.main,
  },
});
