import { StyleSheet } from 'react-native';

const HERO_HEIGHT = 320;

export const styles = StyleSheet.create({
  centerScreen: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#F8FAFC", paddingHorizontal: 24 },
  loadingText: { marginTop: 8, color: "#475569" },
  notFoundText: { color: "#475569", textAlign: "center", fontSize: 18 },
  goBackButton: { marginTop: 24, backgroundColor: "#128AFA", paddingHorizontal: 28, paddingVertical: 12, borderRadius: 9999 },
  goBackButtonText: { color: "white", fontWeight: "600" },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    height: 90,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(226, 232, 240, 0.7)",
  },
  headerContent: {
    position: "absolute",
    top: 48,
    left: 16,
    right: 16,
    zIndex: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerButton: {
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 9999,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  headerButtonActive: {
    backgroundColor: "#e0f2fe",
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: { fontSize: 17, fontWeight: "600", color: "#0F172A", maxWidth: "60%", textAlign: "center" },
  scrollContainer: { paddingBottom: 140 },
  hero: { height: HERO_HEIGHT, backgroundColor: "#E0F2FE" },
  heroImage: { width: "100%", height: "100%" },
  heroOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: "flex-end", padding: 24 },
  heroTitle: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "bold",
    color: "white",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  contentArea: { paddingHorizontal: 20, marginTop: -16, zIndex: 10 },
  card: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  authorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  authorImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#128AFA',
  },
  authorInfo: {
    flex: 1,
  },
  authorLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
    marginBottom: 2,
  },
  authorName: {
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '600',
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chipText: {
    marginLeft: 8,
    color: '#334155',
    fontWeight: '500',
    fontSize: 14,
  },
  descriptionText: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    color: '#475569',
    fontSize: 16,
    lineHeight: 24,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1E293B',
  },
  ingredientList: {
    marginTop: 16,
    gap: 4,
  },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#128AFA',
    borderColor: '#128AFA',
  },
  ingredientText: {
    flex: 1,
    fontSize: 16,
    color: '#334155',
  },
  ingredientTextChecked: {
    textDecorationLine: 'line-through',
    color: '#94A3B8',
  },
  ingredientQty: {
    color: '#64748B',
  },
  instructionsContainer: {
    marginTop: 16,
    gap: 16,
  },
  instructionStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  stepNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#128AFA',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  stepNumberText: {
    color: 'white',
    fontWeight: 'bold',
  },
  stepText: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    color: '#334155',
    paddingTop: 4,
  },
  ctaContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 24,
    paddingBottom: 24,
    paddingTop: 16,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  primaryButton: {
    backgroundColor: "#128AFA",
    paddingVertical: 14,
    borderRadius: 9999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
  },
  primaryButtonText: { textAlign: "center", color: "white", fontSize: 18, fontWeight: "bold" },
});
