import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';

const HERO_HEIGHT = 320;

export const styles = StyleSheet.create({
  centerScreen: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: Colors.neutral.lightest, paddingHorizontal: 24 },
  loadingText: { marginTop: 8, color: Colors.neutral.darker },
  notFoundText: { color: Colors.neutral.darker, textAlign: "center", fontSize: 18 },
  goBackButton: { marginTop: 24, backgroundColor: Colors.primary.main, paddingHorizontal: 28, paddingVertical: 12, borderRadius: 9999 },
  goBackButtonText: { color: Colors.neutral.white, fontWeight: "600" },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    height: 90,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(226, 232, 240, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  headerContent: {
    position: "absolute",
    top: 48,
    left: 16,
    right: 16,
    zIndex: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerButton: {
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 9999,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  headerButtonActive: {
    backgroundColor: "#e0f2fe",
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: { fontSize: 17, fontWeight: "600", color: "#0F172A", maxWidth: "60%", textAlign: "center" },
  scrollContainer: { paddingBottom: 140 },
  hero: { height: HERO_HEIGHT, backgroundColor: "#E0F2FE" },
  heroImage: { width: "100%", height: "100%" },
  heroOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: "flex-end", padding: 24 },
  heroTitle: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "bold",
    color: "white",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  contentArea: { paddingHorizontal: 20, marginTop: -16, zIndex: 10 },
  card: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.5)",
  },
  authorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  authorImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#128AFA',
  },
  authorInfo: {
    flex: 1,
  },
  authorLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
    marginBottom: 2,
  },
  authorName: {
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '600',
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chipText: {
    marginLeft: 8,
    color: '#334155',
    fontWeight: '500',
    fontSize: 14,
  },
  descriptionText: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    color: '#475569',
    fontSize: 16,
    lineHeight: 24,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1E293B',
  },
  ingredientList: {
    marginTop: 16,
    gap: 4,
  },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#128AFA',
    borderColor: '#128AFA',
  },
  ingredientText: {
    flex: 1,
    fontSize: 15,
    color: '#334155',
    fontWeight: '500',
  },
  ingredientTextChecked: {
    textDecorationLine: 'line-through',
    color: '#94A3B8',
  },
  ingredientQty: {
    color: '#64748B',
    fontWeight: '600',
    fontSize: 14,
  },
  ingredientBullet: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#128AFA',
    marginRight: 4,
  },
  instructionsContainer: {
    marginTop: 16,
    gap: 12,
  },
  instructionStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: '#128AFA',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  stepNumber: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#128AFA',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  stepNumberText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  stepText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 24,
    color: '#334155',
    paddingTop: 6,
  },
  ctaContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 24,
    paddingBottom: 40,
    paddingTop: 16,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  primaryButton: {
    backgroundColor: Colors.secondary.main,
    paddingVertical: 14,
    borderRadius: 9999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: Colors.secondary.main,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
  },
  primaryButtonText: { textAlign: "center", color: Colors.neutral.white, fontSize: 18, fontWeight: "bold" },

  // Rating Section Styles
  ratingHeader: {
    marginBottom: 20,
  },
  ratingContent: {
    gap: 20,
  },
  ratingOverview: {
    gap: 16,
  },
  ratingMainDisplay: {
    alignItems: "center",
    gap: 8,
  },
  ratingAverageNumber: {
    fontSize: 48,
    fontWeight: "700",
    color: "#0f172a",
  },
  ratingCountText: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 4,
  },
  ratingDistribution: {
    gap: 8,
    marginTop: 12,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  starLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0f172a",
    width: 30,
  },
  ratingBar: {
    flex: 1,
    height: 8,
    backgroundColor: "#f1f5f9",
    borderRadius: 4,
    overflow: "hidden",
  },
  ratingBarFill: {
    height: "100%",
    backgroundColor: "#FFD700",
    borderRadius: 4,
  },
  ratingRowCount: {
    fontSize: 13,
    fontWeight: "600",
    color: "#64748b",
    width: 30,
    textAlign: "right",
  },
  ratingActions: {
    marginTop: 12,
  },
  rateButton: {
    backgroundColor: "#0ea5e9",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#0ea5e9",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  rateButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  editRatingButton: {
    backgroundColor: "#e0f2fe",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#0ea5e9",
  },
  editRatingButtonText: {
    color: "#0ea5e9",
    fontSize: 15,
    fontWeight: "600",
  },
  noRatingsContainer: {
    alignItems: "center",
    paddingVertical: 24,
    gap: 12,
  },
  noRatingsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#0f172a",
    marginTop: 8,
  },
  noRatingsSubtitle: {
    fontSize: 14,
    color: "#64748b",
    marginBottom: 16,
  },

  // Collapsed Rating Card Styles
  collapsedRatingCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    marginTop: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  collapsedRatingContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  collapsedRatingLeft: {
    flex: 1,
    gap: 8,
  },
  collapsedRatingTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  collapsedRatingInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  collapsedRatingCount: {
    fontSize: 14,
    color: "#64748b",
    fontWeight: "500",
  },
  noRatingsText: {
    fontSize: 13,
    color: "#94a3b8",
  },
  collapsedRatingButton: {
    backgroundColor: "#0ea5e9",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  collapsedRatingButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },

  // === NEW UI IMPROVEMENTS ===

  // Metrics Grid
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
  },
  metricCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  metricIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#128AFA',
    marginTop: 4,
  },
  metricLabel: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontWeight: '600',
  },

  // Colored Tags
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  tag: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#EFF6FF',
    borderWidth: 1.5,
    borderColor: '#BFDBFE',
  },
  tagText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1E40AF',
    textTransform: 'capitalize',
  },
  // Tag type variations
  tagMealType: {
    backgroundColor: '#FEF3C7',
    borderColor: '#FDE68A',
  },
  tagMealTypeText: {
    color: '#92400E',
  },
  tagCookingStyle: {
    backgroundColor: '#D1FAE5',
    borderColor: '#A7F3D0',
  },
  tagCookingStyleText: {
    color: '#065F46',
  },
  tagDietary: {
    backgroundColor: '#FCE7F3',
    borderColor: '#FBCFE8',
  },
  tagDietaryText: {
    color: '#9F1239',
  },

  // Difficulty Badge
  difficultyBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  difficultyEasy: {
    backgroundColor: '#D1FAE5',
    borderWidth: 1.5,
    borderColor: '#10B981',
  },
  difficultyMedium: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1.5,
    borderColor: '#F59E0B',
  },
  difficultyHard: {
    backgroundColor: '#FEE2E2',
    borderWidth: 1.5,
    borderColor: '#EF4444',
  },
  difficultyText: {
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  difficultyTextEasy: {
    color: '#047857',
  },
  difficultyTextMedium: {
    color: '#D97706',
  },
  difficultyTextHard: {
    color: '#DC2626',
  },

  // Source Badge
  sourceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
    marginBottom: 12,
  },
  sourceBadgeAI: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  sourceBadgeHuman: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  sourceBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sourceBadgeTextAI: {
    color: '#1E40AF',
  },
  sourceBadgeTextHuman: {
    color: '#15803D',
  },
  // Scale Button
  scaleButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#EFF6FF',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    width: '85%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 24,
  },
  scaleOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
  },
  scaleOption: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    minWidth: 70,
    alignItems: 'center',
  },
  scaleOptionActive: {
    borderColor: '#0284c7',
    backgroundColor: '#EFF6FF',
  },
  scaleOptionText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#475569',
  },
  scaleOptionTextActive: {
    color: '#0284c7',
  },
  // Equipment Display
  equipmentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingTop: 16,
  },
  equipmentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F0F9FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  equipmentIcon: {
    fontSize: 16,
  },
  equipmentName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E40AF',
  },
  customScaleLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0f172a',
    marginTop: 20,
    marginBottom: 12,
    textAlign: 'center',
  },
  customScaleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  customScaleInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
  },
  customScaleButton: {
    backgroundColor: '#0ea5e9',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  customScaleButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
