import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f9ff',
  },
  gradient: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    backgroundColor: '#fff',
  },
  closeButton: {
    padding: 8,
    marginRight: 12,
  },
  rotateButton: {
    padding: 8,
    marginLeft: 12,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 2,
  },
  recipeTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
  },
  progressSection: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  progressText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0284c7',
  },
  stepCounter: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: '#e0f2fe',
    borderRadius: 999,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#0284c7',
    borderRadius: 999,
  },
  mainContent: {
    flex: 1,
  },
  mainContentLandscape: {
  },
  stepContainer: {
    flex: 1,
  },
  stepContainerLandscape: {
    flex: 1,
  },
  stepContent: {
    padding: 24,
    paddingBottom: 40,
  },
  stepContentLandscape: {
    padding: 28,
    paddingBottom: 32,
  },
  stepNumberBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#0ea5e9',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    marginBottom: 20,
    gap: 8,
  },
  stepNumberText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  criticalBadge: {
    backgroundColor: '#fef3c7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#fbbf24',
  },
  criticalBadgeText: {
    color: '#92400e',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  instructionText: {
    fontSize: 24,
    lineHeight: 36,
    color: '#0f172a',
    fontWeight: '500',
    marginBottom: 32,
  },
  instructionTextLandscape: {
    fontSize: 28,
    lineHeight: 42,
    marginBottom: 28,
    fontWeight: '600',
  },
  completeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e0f2fe',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#0284c7',
    gap: 10,
  },
  completeButtonActive: {
    backgroundColor: '#0284c7',
    borderColor: '#0284c7',
  },
  completeButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0284c7',
  },
  completeButtonTextActive: {
    color: '#fff',
  },
  timerContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 16,
    marginTop: 24,
    borderWidth: 2,
    borderColor: '#fed7aa',
    shadowColor: '#f97316',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  timerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  timerHeaderText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ea580c',
  },
  timerDisplay: {
    alignItems: 'center',
    paddingVertical: 20,
    backgroundColor: '#fff7ed',
    borderRadius: 12,
    marginBottom: 16,
  },
  timerTime: {
    fontSize: 48,
    fontWeight: '700',
    color: '#0f172a',
    fontVariant: ['tabular-nums'],
  },
  timerLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f97316',
    marginTop: 4,
  },
  timerControls: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
  },
  timerButtonPrimary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10b981',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    gap: 8,
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  timerButtonPause: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f59e0b',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    gap: 8,
    shadowColor: '#f59e0b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  timerButtonSecondary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    gap: 8,
    borderWidth: 2,
    borderColor: '#fed7aa',
  },
  timerButtonPrimaryText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  timerButtonSecondaryText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#f97316',
  },
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    gap: 12,
  },
  navigationLandscape: {
    flex: 1,
    flexDirection: 'column',
    borderTopWidth: 0,
    borderLeftWidth: 1,
    borderLeftColor: '#e2e8f0',
    paddingHorizontal: 12,
    paddingVertical: 16,
    justifyContent: 'center',
  },
  navButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    gap: 8,
  },
  prevButton: {},
  nextButton: {},
  navButtonDisabled: {
    opacity: 0.4,
  },
  navButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  navButtonTextDisabled: {
    color: '#94a3b8',
  },
  completionBanner: {
    position: 'absolute',
    top: 80,
    alignSelf: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  completionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  deductButtonContainer: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
  },
  deductButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0284c7',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    gap: 10,
    shadowColor: '#0284c7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  deductButtonSuccess: {
    backgroundColor: '#10b981',
    shadowColor: '#10b981',
  },
  deductButtonDisabled: {
    opacity: 0.6,
  },
  deductButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#fff',
  },
  // Quick Actions Styles
  quickActions: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  quickActionWrapper: {
    alignItems: 'center',
    gap: 4,
  },
  quickActionButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 2,
  },
  quickActionLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: '#64748b',
    textAlign: 'center',
  },
  timerActionButton: {
    backgroundColor: '#fff7ed',
    borderColor: '#fed7aa',
  },
  noteActionButton: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
  },
  reminderActionButton: {
    backgroundColor: '#f5f3ff',
    borderColor: '#e9d5ff',
  },
  reminderActionButtonActive: {
    backgroundColor: '#f5f3ff',
    borderColor: '#c084fc',
  },
  equipmentActionButton: {
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
  },
  timeActionButton: {
    backgroundColor: '#fce7f3',
    borderColor: '#fbcfe8',
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  quickActionTextActive: {
    color: '#8b5cf6',
    fontWeight: '700',
  },
  // Custom Timers Styles
  timersScrollView: {
    maxHeight: 140,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  timersContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  customTimerCard: {
    width: 140,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  customTimerCardRunning: {
    borderColor: '#f97316',
    backgroundColor: '#fff7ed',
  },
  customTimerCardComplete: {
    borderColor: '#10b981',
    backgroundColor: '#f0fdf4',
  },
  customTimerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  customTimerLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
    flex: 1,
  },
  customTimerTime: {
    fontSize: 24,
    fontWeight: '700',
    color: '#0f172a',
    textAlign: 'center',
    marginBottom: 8,
    fontVariant: ['tabular-nums'],
  },
  customTimerControls: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
  },
  customTimerButton: {
    backgroundColor: '#0284c7',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  customTimerButtonSecondary: {
    backgroundColor: '#f1f5f9',
  },
  // Step Notes Styles
  stepNoteDisplay: {
    backgroundColor: '#f0fdf4',
    padding: 14,
    borderRadius: 12,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#10b981',
  },
  stepNoteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  stepNoteTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#10b981',
  },
  stepNoteText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#334155',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalScrollView: {
    flex: 1,
  },
  modalScrollContent: {
    paddingBottom: 16,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 8,
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 15,
    color: '#64748b',
    marginBottom: 20,
    textAlign: 'center',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
    marginBottom: 16,
  },
  modalInputMultiline: {
    minHeight: 120,
    textAlignVertical: 'top',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonCancel: {
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  modalButtonConfirm: {
    backgroundColor: '#0284c7',
  },
  modalButtonTextCancel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#64748b',
  },
  modalButtonTextConfirm: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  // Timer Edit Modal Styles
  timerEditModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    paddingBottom: 0,
    width: '95%',
    maxWidth: 400,
    maxHeight: '98%',
    shadowColor: '#0284c7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  timerEditTitle: {
    fontSize: 20,
    fontWeight: '400',
    color: '#9ca3af',
    marginBottom: 16,
    textAlign: 'center',
  },
  pickerLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  pickerLabelText: {
    fontSize: 11,
    fontWeight: '400',
    color: '#9ca3af',
    width: 70,
    textAlign: 'center',
  },
  pickerContainer: {
    height: 150,
    marginBottom: 16,
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 0,
  },
  pickerColumn: {
    alignItems: 'center',
    position: 'relative',
  },
  pickerScroll: {
    width: 65,
    height: 150,
  },
  pickerScrollContent: {
    paddingVertical: 45,
  },
  pickerItem: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerItemText: {
    fontSize: 18,
    fontWeight: '300',
    color: '#d1d5db',
  },
  pickerItemTextSelected: {
    fontSize: 38,
    fontWeight: '300',
    color: '#0ea5e9',
  },
  colonSeparator: {
    fontSize: 38,
    fontWeight: '300',
    color: '#0ea5e9',
    marginHorizontal: 6,
  },
  pickerBorderTop: {
    position: 'absolute',
    width: '100%',
    height: 1,
    top: 45,
    backgroundColor: '#e5e7eb',
  },
  pickerBorderBottom: {
    position: 'absolute',
    width: '100%',
    height: 1,
    top: 105,
    backgroundColor: '#e5e7eb',
  },
  timerEditButtons: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  timerEditButtonStop: {
    flex: 1,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#e5e7eb',
  },
  timerEditButtonStart: {
    flex: 1,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerEditButtonStartText: {
    fontSize: 17,
    fontWeight: '400',
    color: '#0ea5e9',
  },
  timerEditButtonStopText: {
    fontSize: 17,
    fontWeight: '400',
    color: '#9ca3af',
  },
  // Voice Control Styles
  voiceControlBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 12,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  voiceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#e2e8f0',
  },
  voiceButtonActive: {
    backgroundColor: '#8b5cf6',
    borderColor: '#8b5cf6',
  },
  voiceButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  voiceButtonTextActive: {
    color: '#fff',
  },
  voiceListenButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: '#8b5cf6',
    shadowColor: '#8b5cf6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  voiceListenButtonActive: {
    backgroundColor: '#ef4444',
    shadowColor: '#ef4444',
  },
  voiceListenButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  voiceFeedbackButton: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Measurement Converter Styles
  floatingConverterButton: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#0ea5e9',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0ea5e9',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  converterRow: {
    marginBottom: 16,
  },
  converterUnitContainer: {
    gap: 8,
  },
  converterLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 4,
  },
  unitScroll: {
    maxHeight: 50,
  },
  unitButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#f1f5f9',
    borderWidth: 2,
    borderColor: '#e2e8f0',
    marginRight: 8,
  },
  unitButtonActive: {
    backgroundColor: '#dbeafe',
    borderColor: '#0ea5e9',
  },
  unitButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  unitButtonTextActive: {
    color: '#0ea5e9',
    fontWeight: '700',
  },
  converterArrow: {
    alignItems: 'center',
    marginVertical: 12,
  },
  // Gamification Styles
  achievementBanner: {
    position: 'absolute',
    top: 100,
    left: 40,
    right: 40,
    backgroundColor: '#10b981',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  achievementIcon: {
    fontSize: 36,
  },
  achievementTextContainer: {
    flex: 1,
  },
  achievementTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 3,
  },
  achievementMessage: {
    fontSize: 14,
    fontWeight: '500',
    color: '#d1fae5',
  },
  // Landscape Sidebar Styles
  landscapeControlsSidebar: {
    width: 240,
    backgroundColor: '#fff',
    borderLeftWidth: 1,
    borderLeftColor: '#e2e8f0',
    paddingVertical: 12,
  },
  sidebarSection: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  sidebarSectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  sidebarProgressInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sidebarProgressText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0284c7',
  },
  sidebarStepText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
  },
  sidebarNavButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8fafc',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginVertical: 3,
    gap: 6,
  },
  sidebarNavButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0f172a',
  },
  sidebarQuickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  sidebarActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 6,
    gap: 5,
    flex: 1,
    minWidth: '45%',
  },
  sidebarActionButtonActive: {
    backgroundColor: '#ede9fe',
  },
  sidebarActionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0f172a',
  },
  sidebarVoiceToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    gap: 6,
    marginBottom: 6,
  },
  sidebarVoiceToggleActive: {
    backgroundColor: '#0ea5e9',
  },
  sidebarVoiceText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
  },
  sidebarVoiceTextActive: {
    color: '#fff',
  },
  sidebarVoiceControls: {
    gap: 6,
  },
  sidebarVoiceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10b981',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    gap: 6,
  },
  sidebarVoiceButtonActive: {
    backgroundColor: '#ef4444',
  },
  sidebarVoiceButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  sidebarVoiceFeedbackButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
    paddingVertical: 10,
    borderRadius: 8,
  },
  sidebarTimerCard: {
    backgroundColor: '#fef3c7',
    borderRadius: 6,
    padding: 10,
    marginVertical: 4,
    borderWidth: 2,
    borderColor: '#fde047',
  },
  sidebarTimerCardRunning: {
    backgroundColor: '#dbeafe',
    borderColor: '#60a5fa',
  },
  sidebarTimerCardComplete: {
    backgroundColor: '#d1fae5',
    borderColor: '#34d399',
  },
  sidebarTimerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  sidebarTimerLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#78350f',
    flex: 1,
  },
  sidebarTimerTime: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 8,
  },
  sidebarTimerControls: {
    flexDirection: 'row',
    gap: 6,
  },
  sidebarTimerButton: {
    backgroundColor: '#0f172a',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Automatic Mode Styles
  autoModeOverlay: {
    position: 'absolute',
    top: 12,
    right: 12,
  },
  autoModeTimerCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#0ea5e9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#38bdf8',
    shadowColor: '#0ea5e9',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 6,
  },
  autoModeTimerText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
  },
  // Equipment and Time Modal Styles
  modalHeader: {
    fontSize: 24,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 20,
    textAlign: 'center',
  },
  equipmentList: {
    gap: 24,
  },
  equipmentCategoryTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#64748b',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  equipmentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  equipmentIcon: {
    fontSize: 28,
    marginRight: 12,
  },
  equipmentName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
    flex: 1,
  },
  essentialBadge: {
    backgroundColor: '#fef3c7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#fbbf24',
  },
  essentialText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#92400e',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timeBreakdownContainer: {
    gap: 20,
  },
  timeTotalCard: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  timeTotalInfo: {
    alignItems: 'center',
    gap: 8,
  },
  timeSplitContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  timeCard: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    alignItems: 'center',
    gap: 8,
  },
  timeCardIcon: {
    marginBottom: 4,
  },
  timeCardEmoji: {
    fontSize: 32,
    marginBottom: 4,
  },
  timeProgressBar: {
    width: '100%',
    height: 8,
    backgroundColor: '#e2e8f0',
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 8,
  },
  timeProgressFill: {
    height: '100%',
    borderRadius: 999,
  },
  timeDetailsList: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    gap: 12,
  },
  timeDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeDetailDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 12,
  },
  timeDetailLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#64748b',
    flex: 1,
  },
  timeDetailValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0f172a',
  },
  timeInfoBox: {
    backgroundColor: '#f0f9ff',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  timeInfoText: {
    fontSize: 13,
    color: '#0c4a6e',
    lineHeight: 20,
    textAlign: 'center',
  },
  modalPrimaryButton: {
    backgroundColor: '#0284c7',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  modalPrimaryButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  timeTotalLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timeTotalValue: {
    fontSize: 36,
    fontWeight: '700',
    color: '#0f172a',
  },
  timeCardLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timeCardSubLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: '#94a3b8',
  },
  timeCardValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#0f172a',
  },
});
