import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "@/constants/colors";

const { height: SCREEN_HEIGHT } = Dimensions.get("window");

const inventoryStyle = StyleSheet.create({
  container: { flex: 1 },
  center: { justifyContent: "center", alignItems: "center", flex: 1 },
  safeArea: { flex: 1 },
  head: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 8 },
  title: { fontSize: 26, fontWeight: "bold", color: "#128AFA" },

  // Search & Filter controls
  controlsRow: {
    paddingHorizontal: 16,
    paddingTop: 8,
    gap: 12,
  },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#0f172a",
  },
  filterScroll: {
    paddingVertical: 4,
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "transparent",
  },
  filterChipActive: {
    backgroundColor: "#15803d",
    borderColor: "#15803d",
  },
  filterChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
  },
  filterChipTextActive: {
    color: "#fff",
  },

  // List
  list: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 100,
  },
  itemCard: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  itemCardFresh: {
    borderLeftWidth: 4,
    borderLeftColor: "#10b981",
    backgroundColor: "#fafffe",
  },
  itemCardExpiringSoon: {
    borderLeftWidth: 4,
    borderLeftColor: "#f59e0b",
    backgroundColor: "#fffef9",
    shadowColor: "#f59e0b",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  itemCardExpired: {
    borderLeftWidth: 4,
    borderLeftColor: "#ef4444",
    backgroundColor: "#fffafa",
  },
  itemImg: {
    width: 70,
    height: 70,
    borderRadius: 14,
    marginRight: 14,
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0f172a",
    marginBottom: 4,
  },
  itemQty: {
    fontSize: 14,
    color: "#64748b",
  },
  lowStockLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ef4444",
    marginTop: 2,
  },
  addToCartBtn: {
    padding: 8,
    marginLeft: 8,
  },

  // Quick Add Presets
  quickAddSection: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
  },
  quickAddTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 8,
  },
  quickAddScroll: {
    gap: 8,
  },
  quickAddCard: {
    alignItems: "center",
    marginRight: 12,
    padding: 12,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    minWidth: 80,
  },
  quickAddEmoji: {
    fontSize: 32,
    marginBottom: 6,
  },
  quickAddName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
  },

  // Shopping List
  shoppingListBtnContainer: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  shoppingListBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#15803d",
    paddingVertical: 12,
    borderRadius: 12,
  },
  shoppingListBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  addLowStockBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#f97316",
    paddingVertical: 12,
    borderRadius: 12,
  },
  addLowStockBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  emptyShoppingList: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  shoppingListContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 100,
  },
  shoppingListItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
  },
  shoppingListCheckbox: {
    marginRight: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#15803d",
    alignItems: "center",
    justifyContent: "center",
  },
  shoppingListInfo: {
    flex: 1,
  },
  shoppingListName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0f172a",
    marginBottom: 2,
  },
  shoppingListQty: {
    fontSize: 14,
    color: "#64748b",
  },

  // Bulk Mode
  formHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  bulkModeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  bulkModeBtnActive: {
    backgroundColor: "#dcfce7",
    borderColor: "#16a34a",
  },
  bulkModeBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
  },
  bulkModeBtnTextActive: {
    color: "#16a34a",
  },
  bulkItemsPreview: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "#f0fdf4",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  bulkItemsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#15803d",
    marginBottom: 8,
  },
  bulkItemText: {
    fontSize: 13,
    color: "#166534",
    marginBottom: 4,
  },

  // Quantity Adjustment
  quantityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  qtyBtn: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#f0fdf4",
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  qtyInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    textAlign: "center",
  },

  // Search result count
  resultCountContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  resultCountText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#64748b",
  },

  // Empty states
  loadingText: {
    marginTop: 12,
    fontSize: 15,
    color: "#64748b",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  emptyIconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#f3f4f6",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  emptyText: {
    marginTop: 8,
    fontSize: 20,
    fontWeight: "700",
    color: "#374151",
    textAlign: "center",
  },
  emptyHint: {
    marginTop: 8,
    fontSize: 15,
    color: "#9ca3af",
    textAlign: "center",
    lineHeight: 22,
    paddingHorizontal: 32,
  },
  emptyButton: {
    marginTop: 20,
    backgroundColor: "#128AFA",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  emptyButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },

  search: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  filters: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  scanButton: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.secondary.main,
    paddingVertical: 12,
    borderRadius: 14,
    shadowColor: Colors.secondary.main,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  scanButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  fChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#eef2f7",
  },
  fChipOn: { backgroundColor: "#128AFA" },
  fTxt: { color: "#111827", fontWeight: "600" },
  fTxtOn: { color: "#fff" },
  tile: {
    flex: 1,
    backgroundColor: "#f9fafb",
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
  },
  tileImg: { width: "100%", height: 100, borderRadius: 12, marginBottom: 8 },
  tileName: { fontSize: 15, fontWeight: "600" },
  tileQty: { fontSize: 13, color: "#6b7280" },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 28,
    backgroundColor: Colors.secondary.main,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.secondary.main,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  sheetTitle: { fontSize: 18, fontWeight: "700", marginBottom: 8 },
  sheetOpt: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomColor: "#f3f4f6",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  sheetTxt: { fontSize: 16, fontWeight: "600", color: "#111827" },
  formWrap: { flex: 1 },
  formBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.55)",
    justifyContent: "flex-end",
  },
  formCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    maxHeight: SCREEN_HEIGHT * 0.85,
  },
  formContent: { paddingBottom: 12, gap: 12 },
  formTitle: { fontSize: 20, fontWeight: "700", color: "#111827" },
  formImg: {
    width: "100%",
    height: 140,
    borderRadius: 16,
    marginTop: 12,
    marginBottom: 4,
  },
  label: { fontSize: 14, fontWeight: "600", color: "#374151" },
  input: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  suggestPanel: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    backgroundColor: "#fff",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 2,
  },
  suggestLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#f1f5f9",
  },
  suggestLoadingText: { color: "#475569", fontSize: 14 },
  suggestRow: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#f1f5f9",
  },
  suggestRowHighlight: {
    backgroundColor: "#e0f2fe",
  },
  suggestName: { fontSize: 15, fontWeight: "600", color: "#0f172a" },
  suggestMeta: { marginTop: 2, fontSize: 13, color: "#64748b" },
  suggestEmpty: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    textAlign: "center",
    color: "#64748b",
  },
  unitWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
  unitChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#f3f4f6",
  },
  unitChipOn: { backgroundColor: "#128AFA" },
  unitChipTxt: { color: "#111827", fontWeight: "600" },
  unitChipTxtOn: { color: "#fff" },
  unitPickerContainer: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderColor: "transparent",
  },
  unitPicker: {
    height: 48,
    color: "#0f172a",
  },
  btnRow: { flexDirection: "row", gap: 12, marginTop: 20 },
  formBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  cancelBtn: { backgroundColor: "#f3f4f6" },
  cancelBtnTxt: { color: "#111827" },
  saveBtn: { backgroundColor: "#128AFA" },
  formBtnTxt: { fontSize: 16, fontWeight: "700", color: "#fff" },
  camOverlay: {
    position: "absolute",
    bottom: 40,
    width: "100%",
    alignItems: "center",
  },
  closeCam: {
    position: "absolute",
    top: 40,
    right: 20,
    backgroundColor: "rgba(0,0,0,0.4)",
    borderRadius: 20,
    padding: 8,
  },
  shutter: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 6,
    borderColor: "rgba(255,255,255,0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  shutterInner: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#fff",
  },
  focusLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  topCloseButton: {
    position: "absolute",
    top: 40,
    left: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 3,
  },
  frameCorners: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  frameCorner: {
    position: "absolute",
    width: 36,
    height: 36,
    borderColor: "rgba(255,255,255,0.8)",
    borderWidth: 3,
  },
  frameCorner_tl: {
    top: 30,
    left: 30,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  frameCorner_tr: {
    top: 30,
    right: 30,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },
  frameCorner_bl: {
    bottom: 150,
    left: 30,
    borderRightWidth: 0,
    borderTopWidth: 0,
  },
  frameCorner_br: {
    bottom: 150,
    right: 30,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  reticleOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 0,
  },
  reticleCircle: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
  },
  reticleLineHorizontal: {
    position: "absolute",
    width: 200,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  reticleLineVertical: {
    position: "absolute",
    height: 200,
    width: 1,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  reticlePlus: {
    position: "absolute",
    fontSize: 32,
    color: "rgba(255,255,255,0.9)",
    fontWeight: "600",
  },
  bottomControls: {
    position: "absolute",
    bottom: 40,
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  sideButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  captureButton: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#4a4a4a",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    borderColor: "rgba(255,255,255,0.4)",
  },
  captureInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#ef4444",
  },
  scanIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  modeLabelRow: {
    position: "absolute",
    bottom: 16,
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    gap: 24,
  },
  modeLabel: {
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 1,
  },
  modeActive: {
    color: "#fff",
  },
  modeInactive: {
    color: "rgba(255,255,255,0.4)",
  },
  scanActionButton: {
    marginTop: 12,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(0,0,0,0.4)",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  scanActionText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  scanPrompt: {
    marginTop: 12,
    color: "rgba(255,255,255,0.75)",
    textAlign: "center",
    fontSize: 14,
    fontWeight: "500",
    letterSpacing: 0.4,
  },
  cameraContainer: {
    flex: 1,
    backgroundColor: "black",
    justifyContent: "space-between",
  },
  previewWrapper: {
    flex: 1,
    width: "100%",
  },
  cameraPreview: {
    flex: 1,
    width: "100%",
  },
  previewOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  previewImage: {
    width: "100%",
    height: "100%",
  },
  camOverlayPanel: {
    width: "100%",
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 32,
    backgroundColor: "rgba(0,0,0,0.82)",
    alignItems: "center",
    gap: 16,
  },
  previewRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 2,
  },
  previewItem: {
    color: "#334155",
    fontSize: 14,
  },
  previewCount: {
    fontSize: 12,
    color: "#0284c7",
    fontWeight: "600",
  },
  previewCountLow: {
    color: "#dc2626",
  },
  cameraPermissionText: {
    color: "#fff",
    marginBottom: 16,
  },
  cameraPermissionBtn: {
    backgroundColor: "#128AFA",
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  cameraPermissionBtnText: {
    color: "#fff",
    fontWeight: "600",
  },
  cameraCancelBtn: {
    backgroundColor: "#4b5563",
    padding: 12,
    borderRadius: 8,
  },
  cameraCancelBtnText: {
    color: "#fff",
    fontWeight: "600",
  },
  previewActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
    width: "100%",
  },
  previewSecondaryBtn: {
    flex: 1,
    backgroundColor: "#4b5563",
    padding: 14,
    borderRadius: 10,
  },
  previewSecondaryBtnText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "600",
  },
  previewPrimaryBtn: {
    flex: 1,
    backgroundColor: "#10b981",
    padding: 14,
    borderRadius: 10,
  },
  previewPrimaryBtnText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "600",
  },
});

export default inventoryStyle;
