import { StyleSheet } from "react-native";

export const recipeDatabaseStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#e0f2fe",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#0f172a",
  },
  refreshButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e0f2fe",
  },
  refreshButtonDisabled: {
    opacity: 0.5,
  },
  subtitle: {
    paddingHorizontal: 20,
    fontSize: 15,
    color: "#475569",
    marginBottom: 12,
  },
  providerToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  providerButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  providerButtonActive: {
    backgroundColor: "#e0f2fe",
    borderColor: "#128AFA",
  },
  providerButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#475569",
  },
  providerButtonTextActive: {
    color: "#0f172a",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  loadingText: {
    marginTop: 12,
    color: "#6b7280",
    fontSize: 16,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  errorContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    paddingHorizontal: 32,
    backgroundColor: "#fee2e2",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  errorText: {
    color: "#b91c1c",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 16,
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#128AFAFF",
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 8,
  },
  emptyMessage: {
    fontSize: 15,
    color: "#94a3b8",
    textAlign: "center",
  },
  cardList: {
    gap: 20,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#94a3b8",
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 15,
    elevation: 5,
    marginBottom: 0,
    overflow: "hidden",
  },
  cardImage: {
    width: "100%",
    height: 192,
  },
  cardContent: {
    padding: 20,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#1e293b",
    marginBottom: 8,
  },
  cardDescription: {
    color: "#475569",
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 12,
  },
  ingredientsSection: {
    marginBottom: 16,
    gap: 4,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0f172a",
  },
  ingredientItem: {
    color: "#334155",
    fontSize: 14,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    paddingTop: 14,
  },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  metaText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#0f172a",
  },
  sourcePill: {
    backgroundColor: "#e0f2fe",
  },
  matchHighPill: {
    backgroundColor: "#d1fae5",
  },
  matchMediumPill: {
    backgroundColor: "#fed7aa",
  },
  matchLowPill: {
    backgroundColor: "#fecaca",
  },
  categoryPill: {
    backgroundColor: "#f1f5f9",
  },
  areaPill: {
    backgroundColor: "#fef3c7",
  },
  tagPill: {
    backgroundColor: "#f1f5f9",
  },
  actionButton: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "rgba(18,138,250,0.12)",
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0f172a",
  },
  partialSection: {
    marginTop: 16,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#fef3c7",
    borderWidth: 1,
    borderColor: "#fcd34d",
    gap: 6,
  },
  partialMatchItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  partialMatchText: {
    flex: 1,
    fontSize: 13,
    color: "#78350f",
  },
  partialMatchPercentage: {
    fontSize: 11,
    fontWeight: "600",
    color: "#92400e",
    backgroundColor: "#fef9c3",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  missingSection: {
    marginTop: 16,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 6,
  },
  missingSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  canSuggestHint: {
    fontSize: 11,
    color: "#128AFA",
    fontWeight: "600",
  },
  missingItem: {
    fontSize: 13,
    color: "#1e293b",
  },
  moreMissing: {
    fontSize: 13,
    color: "#475569",
  },
  suggestButton: {
    marginTop: 8,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#128AFA",
    alignItems: "center",
    justifyContent: "center",
  },
  suggestButtonDisabled: {
    opacity: 0.6,
  },
  suggestButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ffffff",
  },
  suggestionError: {
    marginTop: 6,
    fontSize: 13,
    color: "#dc2626",
  },
  suggestionErrorContainer: {
    marginTop: 8,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#fecaca",
    gap: 8,
  },
  retrySmallButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: "#128AFA",
    alignSelf: "flex-start",
  },
  retrySmallButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  alternativeList: {
    marginTop: 10,
    gap: 10,
  },
  alternativeHeader: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 4,
  },
  alternativeCard: {
    padding: 12,
    borderRadius: 10,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 6,
  },
  alternativeTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#0f172a",
  },
  alternativeDescription: {
    fontSize: 13,
    color: "#475569",
  },
  altIngredients: {
    marginTop: 6,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    gap: 3,
  },
  altIngredientsLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
  },
  altIngredientItem: {
    fontSize: 12,
    color: "#64748b",
  },
  altMoreIngredients: {
    fontSize: 11,
    color: "#94a3b8",
    fontStyle: "italic",
  },
  moreAlternatives: {
    fontSize: 12,
    color: "#64748b",
    textAlign: "center",
    fontStyle: "italic",
    marginTop: 4,
  },
  noAlternatives: {
    fontSize: 13,
    color: "#64748b",
    fontStyle: "italic",
    marginTop: 8,
  },
  substituteItem: {
    marginTop: 8,
    paddingLeft: 8,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  substituteReason: {
    fontSize: 11,
    color: "#64748b",
    fontStyle: "italic",
    marginTop: 4,
    paddingLeft: 12,
    lineHeight: 16,
  },
  tappableIngredient: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginVertical: 4,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  tappableIngredientLoading: {
    backgroundColor: "#f1f5f9",
    borderColor: "#128AFA",
  },
  tappableIngredientActive: {
    backgroundColor: "#e0f2fe",
    borderColor: "#128AFA",
  },
  missingItemTappable: {
    fontSize: 13,
    color: "#1e293b",
    fontWeight: "500",
    flex: 1,
  },
  ingredientLoader: {
    marginLeft: 8,
  },
  substitutesList: {
    marginTop: 8,
    marginLeft: 16,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: "#128AFA",
    gap: 8,
  },
  substitutesHeader: {
    fontSize: 12,
    fontWeight: "600",
    color: "#128AFA",
    marginBottom: 4,
  },
  substituteHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  substituteIngredient: {
    fontSize: 13,
    fontWeight: "600",
    color: "#0f172a",
    flex: 1,
  },
  notInInventoryBadge: {
    backgroundColor: "#fef3c7",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#fcd34d",
  },
  notInInventoryText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#92400e",
  },
});
